name: Slack Notification

on:
  pull_request:
    types: [opened, closed]

jobs:
  send_slack_notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification for PR creation
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: pullRequest
          custom_payload: |
            {
              "attachments": [{
                "color": "good",
                "title": "New Pull Request Opened",
                "text": "A new pull request has been opened by ${{ github.event.pull_request.user.login }}.\nTitle: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nDescription: ${{ github.event.pull_request.body }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack Notification for PR merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: pullRequest
          custom_payload: |
            {
              "attachments": [{
                "color": "good",
                "title": "Pull Request Merged",
                "text": "A pull request has been merged by ${{ github.event.pull_request.merged_by.login }}.\nTitle: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\nDescription: ${{ github.event.pull_request.body }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
